$modelname "sg552_01.mdl"

$include "F:\tools\Sandstorm-Compile-Sources\scale.qci"

$include "F:\tools\Sandstorm-Compile-Sources\sandstorm_deltas_macros.qci"

$include "DefineBones.qci"

$bodygroup "weapon"
{
	studio "SKM_1P_SG552.smd"
}
$bodygroup "mag"
{
	studio "SKM_1P_SG552_Magazine_20.smd"
}

//$include "Bonemerge.qci"

$include "weightlist.qci"

$include "anims.qci"

$include "F:\tools\Sandstorm-Compile-Sources\gmod_bones_follow_sandstorm.qci"

